using UnityEngine;
using UnityEngine.SceneManagement;
using System.Collections;

public class PortalTrigger : MonoBehaviour
{
    public string sceneToLoad; // T√™n m√†n h√¨nh c·∫ßn chuy·ªÉn

    private void OnTriggerEnter2D(Collider2D other)
    {
        if (other.CompareTag("Player"))
        {
            Debug.Log("Player entered portal, loading scene: " + sceneToLoad);
            StartCoroutine(LoadNextScene());
        }
    }

    // üëâ Coroutine ch·ªù 1 gi√¢y r·ªìi chuy·ªÉn scene
    IEnumerator LoadNextScene()
    {
        yield return new WaitForSeconds(3f);
        SceneManager.LoadScene(sceneToLoad);
    }
}
